" Numbering
set number
set relativenumber

set autoindent
" set smartindent
set tabstop=2
set backspace=indent,eol,start
set showmatch
set incsearch
set ignorecase
set smartcase
set laststatus=2
set spell spelllang=en_us
set nobackup
set mouse=a
set showcmd
set matchpairs+=<:>
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ [BUFFER=%n]\ %{strftime('%c')}
nnoremap <Left>  :echoe "Use h"<CR>
nnoremap <Right> :echoe "Use l"<CR>
nnoremap <Up>    :echoe "Use k"<CR>
nnoremap <Down>  :echoe "Use j"<CR>
" ...and in insert mode
inoremap <Left>  <ESC>:echoe "Use h"<CR>
inoremap <Right> <ESC>:echoe "Use l"<CR>
inoremap <Up>    <ESC>:echoe "Use k"<CR>
inoremap <Down>  <ESC>:echoe "Use j"<CR>
set noerrorbells visualbell t_vb=
" New Mappings
" 'Q' in normal mode enters Ex mode. You almost never want this
nmap Q <Nop> 
" make Y effect to end of line instead of whole line
nmap Y y$

call plug#begin('~/.vim/plugged')
Plug 'junegunn/goyo.vim'
Plug 'jacoborus/tender.vim'
Plug 'ycm-core/YouCompleteMe', { 'do': './install --ts-completer' }
call plug#end()

if (has("termguicolors"))
 set termguicolors
endif

syntax enable
colorscheme tender
