set number
set relativenumber

set tabstop=2
set shiftwidth=2
set softtabstop=2
set expandtab
set autoindent

set backspace=indent,eol,start
set showmatch
set incsearch
set ignorecase
set smartcase
set laststatus=2
set spell spelllang=en_us
set nobackup
set mouse=a
set showcmd
set matchpairs+=<:>
set statusline=%F%m%r%h%w\ [FORMAT=%{&ff}]\ [TYPE=%Y]\ [POS=%l,%v][%p%%]\ [BUFFER=%n]\ %{strftime('%c')}
set noerrorbells visualbell t_vb=

set mousehide

set scrolloff=4

" New Mappings
" 'Q' in normal mode enters Ex mode. You almost never want this
nmap Q <Nop> 
" make Y effect to end of line instead of whole line
nmap Y y$
" Instant auto corrects
nmap <C-z> 1z=
imap <C-g> <esc>[S<C-z>A
" Better window switching
nnoremap <C-w>k <C-k><CR>
nnoremap <C-w>j <C-j><CR>
nnoremap <C-w>h <C-h><CR>
nnoremap <C-w>l <C-l><CR>
" useful for writing, start at the very bottom
noremap B GA
" useful for notes, creates a line 
noremap <c-l> 81i-<esc>o
" move lines up or down
nnoremap <c-j> :m .+1<CR>==
nnoremap <c-k> :m .-2<CR>==
inoremap <c-j> <Esc>:m .+1<CR>==gi
inoremap <c-k> <Esc>:m .-2<CR>==gi
vnoremap <c-j> :m '>+1<CR>gv=gv
vnoremap <c-k> :m '<-2<CR>gv=gv
" insert the current date
nnoremap <c-t> :put =strftime('%Y-%m-%d')


call plug#begin('~/.vim/plugged')
  " Plug 'junegunn/goyo.vim'
  Plug 'jacoborus/tender.vim'
	Plug 'reedes/vim-colors-pencil'
  Plug 'reedes/vim-litecorrect'	
	Plug 'reedes/vim-pencil'
	Plug 'reedes/vim-lexical'
  Plug 'ycm-core/YouCompleteMe', { 'do': './install --ts-completer' }
	Plug 'airblade/vim-gitgutter'
	Plug 'LucHermitte/lh-vim-lib'
  Plug 'LucHermitte/local_vimrc'
	Plug 'tpope/vim-commentary'
	Plug 'tpope/vim-surround'
	Plug 'zxqfl/tabnine-vim'
  Plug 'logico/typewriter-vim'
  Plug 'ap/vim-css-color'
call plug#end()

" Plugin settings
" local vim
let g:local_vimrc = ['._vimrc_local.vim', '_vimrc_local.vim']
call lh#local_vimrc#munge('whitelist', $HOME) " Auto accept local_vim

" Pencil
let g:pencil#wrapModeDefault = 'soft'   " default is 'hard'
au BufNewFile,BufFilePre,BufRead *.md set filetype=markdown

" Per file
set nocompatible
filetype plugin on

augroup litecorrect
  autocmd!
  autocmd FileType markdown,mkd call litecorrect#init()
														\ | call pencil#init()
  autocmd FileType textile call litecorrect#init()
augroup END

augroup lexical
  autocmd!
  autocmd FileType markdown,mkd call lexical#init()
augroup END

if (has("termguicolors"))
 set termguicolors
endif

syntax enable
colorscheme tender
"colorscheme pencil
"colorscheme typewriter

"----------------------------------------------------
" Spelling corrections
" ---------------------------------------------------
iab shoudl should
iab taht that
