#!/bin/bash
# A basic script to automate making tests
# Args: path (path to the tests folder) [REQUIRED]
#       name (name of the file to make a test for) [OPTIONAL]
# passing in no args will make tests for every file that doesn't already have a test

if [ $# -eq 0 ]; then
  echo must supply at least a path to tests
	exit 1
fi

# decide how many files to make
if [ $# -gt 1 ]; then 
  CHANGEDFILES=("${@:2}")
else
  CHANGEDFILES=($(git status --porcelain | grep "^A" | cut -c 4-))
fi
	
# gets all files that have been added in this commit
for newFile in "${CHANGEDFILES[@]}"; do
	# get just the file name and extension
	fileName="${newFile##*/}"
	fileExten="${fileName##*.}"
	fileNoExten="${fileName%.*}"
	testFile="$fileNoExten.test.$fileExten"
	
	# check if there is already a test file
	if [ -f "$1/$testFile" ]; then
	  echo test file exists for $newFile -- skipping.
  else
    touch $1/$testFile
		echo test file for $newFile created
	fi
done



